import { jsPDF } from "jspdf";
import { StoryboardData } from "../types";

export const generatePDF = (story: StoryboardData) => {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;

  // Title Page
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text(story.title, pageWidth / 2, pageHeight / 3, { align: "center" });
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(story.purpose, pageWidth / 2, pageHeight / 3 + 15, { align: "center" });

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text("Generated by SpectraTales", pageWidth / 2, pageHeight - 20, { align: "center" });

  // Content Pages
  story.pages.forEach((page, index) => {
    doc.addPage();

    // Image area
    if (page.image_url) {
      try {
        const imgProps = doc.getImageProperties(page.image_url);
        const imgRatio = imgProps.width / imgProps.height;
        const printWidth = pageWidth - (margin * 2);
        const printHeight = printWidth / imgRatio;

        // Center image vertically in top half
        const yPos = margin + 10;
        doc.addImage(page.image_url, "PNG", margin, yPos, printWidth, printHeight);
      } catch (e) {
        // Fallback if image fails to load into PDF
        doc.rect(margin, margin + 10, pageWidth - (margin * 2), 100);
        doc.text("Image Error", pageWidth / 2, margin + 60, { align: "center" });
      }
    }

    // Text area (bottom half)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(0);
    
    // Split text into lines
    const textLines = doc.splitTextToSize(page.text, pageWidth - (margin * 2));
    const textY = pageHeight * 0.65;
    
    doc.text(textLines, pageWidth / 2, textY, { align: "center" });

    // Page number
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(`${index + 1}`, pageWidth - 10, pageHeight - 10);
  });

  doc.save(`${story.title.replace(/\s+/g, "_")}_SpectraTales.pdf`);
};
